[book]
authors = ["dbasrai"]
language = "en"
multilingual = false
src = "src"
title = "Stand-up 101 by Diya Basrai"

[build]
build-dir = "/home/diya/Documents/dbasrai.github.io/standup101"
create-missing = false
